# Generated by Django 2.1.7 on 2019-03-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, verbose_name='nombre')),
                ('lugar', models.CharField(max_length=45, verbose_name='ciudad/Departamento')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('direccion', models.CharField(max_length=45, verbose_name='dirección')),
                ('telefono', models.CharField(max_length=10, verbose_name='telefono')),
                ('nit_cedula', models.IntegerField(verbose_name='cedula')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='nombre')),
                ('precio', models.PositiveIntegerField(verbose_name='precio')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('total', models.PositiveIntegerField(verbose_name='total')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='productos',
            field=models.ManyToManyField(related_name='pedido', to='facturas.Producto'),
        ),
    ]
