# Generated by Django 2.1.7 on 2019-03-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(default=2, verbose_name='cantidad'),
            preserve_default=False,
        ),
    ]
